force-app/main/default/objects/Routing_Configuration__mdt/Routing_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Routing Configuration</label>
    <pluralLabel>Routing Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Routing_Configuration__mdt/fields/Queue__c.field-meta.xml
<CustomField>
    <fullName>Queue__c</fullName>
    <label>Queue</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Routing_Configuration__mdt/fields/Routing_Chinese__c.field-meta.xml
<CustomField>
    <fullName>Routing_Chinese__c</fullName>
    <label>Routing Chinese</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Routing_Configuration__mdt/fields/Routing_English__c.field-meta.xml
<CustomField>
    <fullName>Routing_English__c</fullName>
    <label>Routing English</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Routing_Configuration__mdt/fields/Routing_French__c.field-meta.xml
<CustomField>
    <fullName>Routing_French__c</fullName>
    <label>Routing French</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Routing_Configuration__mdt/fields/Routing_German__c.field-meta.xml
<CustomField>
    <fullName>Routing_German__c</fullName>
    <label>Routing German</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Routing_Configuration__mdt/fields/Routing_Italian__c.field-meta.xml
<CustomField>
    <fullName>Routing_Italian__c</fullName>
    <label>Routing Italian</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Routing_Configuration__mdt/fields/Routing_Portuguese__c.field-meta.xml
<CustomField>
    <fullName>Routing_Portuguese__c</fullName>
    <label>Routing Portuguese</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseRoutingConfigurationTest.cls
@IsTest
private class CaseRoutingConfigurationTest {
   
    @IsTest static void CaseRoutingConfigurationTest() {
        String queue = 'Payment_Department';
        Routing_Configuration__mdt expectedRouting = [
                SELECT Id, DeveloperName, Queue__c, Routing_Chinese__c, Routing_English__c,
                        Routing_French__c, Routing_German__c, Routing_Italian__c,
                        Routing_Portuguese__c
                FROM Routing_Configuration__mdt
                WHERE DeveloperName = :queue
        ];

        Routing_Configuration__mdt routing = CaseRoutingConfiguration.getInstance().getRoutingData(queue);

        System.assertEquals(expectedRouting, routing); //id w expected
    }
}